### ISSUE TITLE
怎么拓展新的插件啊

### ISSUE THREAD

**Issue by link-ding** [Leptune/vim-for-coding#3]
怎么在你现在已有的情况下,再去拓展新的插件啊. 我加入了新的 Plugin 之后 用 Bundel install 你所有的已有的都出现error 我的好像是成了 但是实际没有在vim中出现

**Comment by Leptune** [comment]
你好，为了快速的安装，因此该项目里Bundle的所有插件都移除了.git目录，无法用`BundleInstall`和`BundleUpdate`等命令。
所以若要拓展新的插件的话，请先按照下面步骤进行手动安装：（假设要拓展rking/ag.vim）
1. 编辑~/.vimrc文件，在插件列表中加入：  Plugin 'rking/ag.vim'
2. 在终端运行：`git clone --recursive --depth=1 'https://github.com/rking/ag.vim.git' '~/.vim/bundle/ag.vim'`
3. 重启vim即可
